### ISSUE TITLE
[BUG] SSMR talent Orator 1 lacks the word "reaction"

### ISSUE THREAD

**Issue by compcon** [massif-press/ssmr-data#1]
<strong>Submitted At: </strong> 10/13/2023 15:32:19<br><br><strong>Source: </strong> Siren's Song: A Mountain's Remorse<br><br><strong>Incorrect Text/Data: </strong><br>From Orator 1: "Gain the Convincing Rhetoric"<br><br><strong>Correct Text/Data: </strong><br> "Gain the Convincing Rhetoric reaction"<br>

**Comment by msprijatelj** [comment]
Closed in [1.6.6](https://github.com/massif-press/ssmr-data/commit/797f4a73b6ef1570507e0990396b6187c995f13f)
